# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ./secrets/homedirs.nix
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  services.zfs.autoScrub = {
    enable = true;
    interval = "monthly";
  };

  fileSystems."/" =
    { device = "ancilla/root";
      fsType = "zfs";
    };
  fileSystems."/nix" =
    { device = "ancilla/nix";
      fsType = "zfs";
    };
  fileSystems."/home" =
    { device = "ancilla/home";
      fsType = "zfs";
    };
  fileSystems."/boot" =
    { device = "nix/boot";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/zd0"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
