# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

let
  zfs = dataset: { device = dataset; fsType = "zfs"; };
in {
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  sound.enable = true;

  services.zfs.autoScrub = {
    enable = true;
    interval = "*-*-01 01:15:00";
  };

  # Need to hard-code these so the system can start booting.
  fileSystems."/" = zfs "ancilla/root";
  fileSystems."/nix" = zfs "internal/nix";

  # also, check this out:
  # https://github.com/cleverca22/nixos-configs/blob/master/rescue_boot.nix
  # adds a boot menu entry that boots right into the NixOS installer, suitable
  # as a rescue system with more capability (probably) than the initrd.

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5A92-D54D";
    fsType = "vfat";
  };

  fileSystems."/alt-boot" = {
    device = "/dev/disk/by-id/nvme-WUS3BA138C7P3E3_A06F1084-part1";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-label/nvme-swap-64"; }
  ];

  nix.maxJobs = lib.mkDefault 4;
}
