#!/usr/bin/env zsh
#
# Simple script for pushing configurations to other computers in the house.

set -e

function die {
	echo "$@" > /dev/stderr
	exit 1
}

cd /etc/nixos

TARGET="$1"; shift

case $1 in
  diff)
    trap "rm -f /tmp/$$" EXIT
    nix build -o /tmp/$$ ".#nixosConfigurations.$TARGET.config.system.build.toplevel" |& nom
    nvd diff built/$TARGET /tmp/$$
    exit
    ;;
  *)
esac

ssh -o BatchMode=yes root@$TARGET true || die "Unable to ssh root@$TARGET noninteractively"

# This is a gross hack to create a gcroot for the built system, so we don't have
# to rebuild it ex nihilo each time.
nix build -o built/$TARGET ".#nixosConfigurations.$TARGET.config.system.build.toplevel" |& nom

# Build was successful, so stage the configs on the target as a reference
command rsync -a --info=progress2 \
	--chmod=D0555,F0444 \
	--exclude='/.git/' \
	--delete --delete-excluded \
	/etc/nixos/ root@$TARGET:/etc/nixos/

# And finally actually install the new system configuration
nixos-rebuild --target-host "$TARGET" --flake ".#$TARGET" --impure "$@" |& nom

# TODO: copy shared/ and system-specific configuration to the target.
