#!/usr/bin/env zsh
#
# Simple script for pushing configurations to other computers in the house.

set -e

function die {
	echo "$@" > /dev/stderr
	exit 1
}

TARGET="$1"; shift
ssh -o BatchMode=yes root@$TARGET true || die "Unable to ssh root@$TARGET noninteractively"

cd /etc/nixos
nixos-rebuild --target-host "$TARGET" --flake ".#$TARGET" --impure "$@"

# TODO: copy shared/ and system-specific configuration to the target.
