# This file was generated by go2nix.
self: super:

{
  skicka = self.buildGoPackage rec {
    name = "skicka-${version}";
    version = "20160905-${self.stdenv.lib.strings.substring 0 7 rev}";
    rev = "8ed55aecb87c31d74c797856c2214e68790111fb";

    goPackagePath = "github.com/google/skicka";

    src = self.fetchgit {
      inherit rev;
      url = "https://github.com/google/skicka.git";
      sha256 = "0iz27s76ayy2ydzxwi1a0rw14d5rv96yy2w53r09l6n3fyg392k6";
    };

    goDeps = ./skicka-deps.nix;

    # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
    meta = {
    };
  };
}
