# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/cheggaaa/pb";
    fetch = {
      type = "git";
      url = "https://github.com/cheggaaa/pb";
      rev = "d7e6ca3010b6f084d8056847f55d7f572f180678";
      sha256 = "1n6r262dqcf3f3dd5h4shq9g1v7nci1rxpaishrj9nl68wl5a2dd";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "737072b4e32b7a5018b4a7125da8d12de90e8045";
      sha256 = "09ni8bmj6p2b774bdh6mfcxl03bh5sqk860z03xpb6hv6yfxqkjm";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "41d678d1df78cd0410143162dff954e6dc09300f";
      sha256 = "1gcw2850nghsfi3m98ibsxs8bwqzhdjsgiznrr9ymarzn58v3357";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "f2499483f923065a842d38eb4c7f1927e6fc6e6d";
      sha256 = "0q1ps8igfczfafk39hkp8gs57s6qxjvf2c48hiq00p873agz0x7s";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "314dd2c0bf3ebd592ec0d20847d27e79d0dbe8dd";
      sha256 = "1d2wshi84k7y6c4scmp9h3nbbig859icfnsj8r8j9wavhpphvqb2";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "dfa61ae24628a06502b9c2805d983b57e89399b5";
      sha256 = "190s98m9yzjj46bmpfs5v8mb3j916r9ds3b2d7agm5pzmjms8dcr";
    };
  }
  {
    goPackagePath = "gopkg.in/gcfg.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/gcfg.v1";
      rev = "27e4946190b4a327b539185f2b5b1f7c84730728";
      sha256 = "0vbif6dllrghqvs4ib57m7v5zkdl4qlp572jl5dx98p084v61203";
    };
  }
  {
    goPackagePath = "gopkg.in/warnings.v0";
    fetch = {
      type = "git";
      url = "https://gopkg.in/warnings.v0";
      rev = "8a331561fe74dadba6edfc59f3be66c22c3b065d";
      sha256 = "1d4cjdqniimrpwbiav8ncw920x5lmf3wrsq1npk98y29vs5jhlhv";
    };
  }
]
