#!/usr/bin/env bash

: << =cut

=head1 NAME

certificates -- monitors the expiration date of SSL certificates

=head1 CONFIGURATION

This graph only has one mandatory setting:

[certificates]
  env.domains www.example.com webmail.example.com ftp.example.com

It will query https://$domain for each domain to get the certificate information.

Certs are considered to be WARN when they expire in three days and CRITICAL if
they expire in <1 day.

You can optionally specify a hostname for it:

[certificates]
  env.host_name example.com

It will report itself as belonging to the node "example.com".

=head1 AUTHOR

Written by ToxicFrog

=head1 LICENSE

MIT

=head1 MAGIC MARKERS

 #%# family=contrib

=cut

set -e
source "${MUNIN_LIBDIR}/plugins/plugin.sh"

if [[ "$1" = "config" ]]; then
  [[ $host_name ]] && echo "host_name $host_name"
  echo 'graph_title Certificate Lifetime'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_scale no'
  echo 'graph_vlabel lifetime in days'
  echo 'graph_info Time remaining before certificate expiration'
  echo 'graph_category security'
  for domain in $domains; do
    name="${domain//./_}"
    echo "$name.label $domain"
    echo "$name.warning 3:"
    echo "$name.critical 1:"
  done
  exit 0
fi

now=$(date +%s)
for domain in $domains; do
  name="${domain//./_}"
  expires=$(date +%s -d "$(curl --insecure -v -I https://$domain 2>&1 | grep 'expire date:' | cut -d: -f2-)")
  echo "$name.value $(( (expires - now) / (60*60*24) ))"
done
