#!/usr/bin/env bash

: << =cut

=head1 NAME

ssh__uptime - Plugin to measure uptime on remote hosts

=head1 CONFIGURATION

These are the default settings:

[ssh_host.tld_uptime]
  env.ssh_target munin@host.tld

Unless you have a "munin" user on the target, you may need to change this.

=head1 AUTHOR

Written by B. Kelly, based on the local uptime plugin by Nicolas Salles

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

source $MUNIN_LIBDIR/plugins/plugin.sh

host_name="$(basename "$0" | cut -d_ -f2)"
ssh_target="${ssh_target:=munin@$host_name}"

if [[ "$1" == "autoconf" ]]; then
        echo yes
        exit 0
fi

if [[ "$1" = "config" ]]; then
        echo "host_name $host_name"
        echo 'graph_title Uptime'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel uptime in days'
        echo 'graph_category system'
        echo 'uptime.label uptime'
        echo 'uptime.draw AREA'
        print_warning uptime
        print_critical uptime
        exit 0
fi

ssh "$ssh_target" cat /proc/uptime \
  | awk '{printf "uptime.value %.2f\n",$1/86400}'
