#!/usr/bin/env bash

: << =cut

=head1 NAME

zpool_health -- monitors zpool component health

=head1 CONFIGURATION

[zpool-health]
  env.pools tank backup
  env.zpool /sbin/zpool

If 'pools' is unset, all pool returned by "zpool status" will be monitored.
If 'zpool' is unset, it will try to find it with 'type'.

=head1 AUTHOR

Written by Rebecca Kelly (ToxicFrog)

=head1 LICENSE

MIT

=head1 MAGIC MARKERS

 #%# family=contrib

=cut

shopt -s lastpipe

ZPOOL=${zpool:=$(type -p zpool)}

if [[ "$1" == "autoconf" ]]; then
  if [[ ! $ZPOOL || ! -x $ZPOOL ]]; then
    echo "no (zpool command not found or not executable)"
  elif (( $($ZPOOL list -H -o name | wc -l) < 1 )); then
    echo "no (no pools present)"
  else
    echo yes
  fi
  exit 0
fi

# dimension name title fields...
# e.g dimension recv rx draw:AREA type:DERIVE min:0
function dimension {
  name="$1"
  echo "$name.label $name"
  shift
  while [[ "$1" ]]; do
    local k="${1%%:*}"
    local v="${1#*:}"
    if [[ $k == cdef ]]; then v="$name,$v"; fi
    echo "$name.$k $v"
    shift
  done
}

if [[ "$1" == "config" ]]; then
  cat <<EOF
graph_title ZPool Device Health
graph_category fs
graph_args --base 1000 -l 0
graph_scale no
graph_vlabel device count
graph_info A breakdown of all block devices used in zpools by health status
EOF
  dimension ONLINE type:GAUGE draw:AREA colour:00ff00
  dimension SLOW type:GAUGE draw:AREA colour:0080ff warning:0:0
  for status in DEGRADED ERROR; do
    dimension $status type:GAUGE draw:AREA colour:ff8000 warning:0:0
  done
  for status in OFFLINE REMOVED UNAVAIL FAULTED; do
    dimension $status type:GAUGE draw:AREA colour:ff0000 critical:0:0
  done
  exit 0
fi

## fetch ##

declare -A disks=()
$ZPOOL status -LsP $pools \
| fgrep /dev/ \
| sed -E 's,[ \t]+,\t,g' \
| while read dev state rerr werr cerr slow; do
    if (( slow )) && [[ $state == ONLINE ]]; then
      state="SLOW"
    fi
    if (( rerr + werr + cerr )) && [[ $state == ONLINE || $state == SLOW ]]; then
      state="ERROR"
    fi
    (( disks[$state]++ ))
done
for state in ONLINE SLOW DEGRADED ERROR OFFLINE REMOVED UNAVAIL FAULTED; do
  echo "$state.value ${disks[$state]:=0}"
done
